# Generated by Django 3.1.7 on 2021-02-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210227_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='complete_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complete address (optional)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='User (optional)'),
        ),
    ]
