# Generated by Django 3.1.6 on 2021-02-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ('-date_placed',)},
        ),
    ]
