# Generated by Django 3.1.7 on 2021-03-28 02:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210328_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
