# Generated by Django 3.1.7 on 2021-04-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210328_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='color_variation_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
