# Generated by Django 3.1.6 on 2021-02-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='customer',
        ),
    ]
