# Generated by Django 3.1.7 on 2021-03-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
