# Generated by Django 3.1.7 on 2021-03-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210327_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='transaction_date',
            new_name='created_at',
        ),
    ]
