# Generated by Django 3.1.6 on 2021-02-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_orderproduct_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
    ]
