# Generated by Django 3.1.6 on 2021-02-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_order_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
