# Generated by Django 3.1.7 on 2021-04-08 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210401_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagItemVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Storage Size', 'Storage Size'), ('Color Family', 'Color Family')], default='Storage Size', max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bagitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.bagitem')),
            ],
        ),
    ]
