# Generated by Django 3.1.6 on 2021-02-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderproduct_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='confirmed',
            new_name='selected',
        ),
    ]
