# Generated by Django 3.1.7 on 2021-04-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_bagitemvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagitem',
            name='variation_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
