# Generated by Django 3.1.7 on 2021-04-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_bagitem_variation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitemvariation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
