# Generated by Django 3.1.6 on 2021-02-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-transaction_date',)},
        ),
    ]
