# Generated by Django 3.1.7 on 2021-04-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20210408_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagitem',
            name='variation_category',
            field=models.CharField(blank=True, choices=[('Storage Size', 'Storage Size'), ('Color Family', 'Color Family')], default='Storage Size', max_length=30),
        ),
        migrations.AddField(
            model_name='bagitem',
            name='variation_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='BagItemVariation',
        ),
    ]
