# Generated by Django 3.1.7 on 2021-04-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20210408_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagitem',
            name='variation_category',
        ),
        migrations.RemoveField(
            model_name='bagitem',
            name='variation_name',
        ),
        migrations.AddField(
            model_name='bagitem',
            name='color_variation_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bagitem',
            name='storage_variation_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
