# Generated by Django 3.1.7 on 2021-02-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile_number',
        ),
    ]
