# Generated by Django 3.1.7 on 2021-04-01 05:51

import backend.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to=backend.store.models.display_picture_path),
        ),
    ]
