# Generated by Django 3.1.7 on 2021-02-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_customer_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
