# Generated by Django 3.1.7 on 2021-04-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210401_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Samsung', 'Samsung'), ('Iphone', 'Iphone'), ('Vivo', 'Vivo'), ('Oppo', 'Oppo')], max_length=20, null=True),
        ),
    ]
