# Generated by Django 3.1.7 on 2021-03-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210227_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'Brand new'), ('Used', 'Used')], default='New', max_length=20, null=True),
        ),
    ]
