# Generated by Django 3.1.7 on 2021-03-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'Brand new'), ('Used', 'Used')], default='New', max_length=20),
        ),
    ]
