# Generated by Django 3.1.7 on 2021-03-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210318_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Brand new', 'Brand new'), ('Used', 'Used')], default='Brand new', max_length=20),
        ),
    ]
